### PR TITLE
features added from downstream

### PR DESCRIPTION
**Pull request by eyehwan**
1. add release information in github
2. Support --proxy parameter in perceval/backend
3. add pull_linked_issues in github

### CODE REVIEW

**Comment by sduenas** [comment]
Thanks for the PR @eyehwan but would you mind to open separate PRs for each one of the new functionalities. Thanks

**Comment by eyehwan** [comment]
Sure, I will do it.

**Comment by sduenas** [comment]
@eyehwan do you need any help with this?

**Comment by eyehwan** [comment]
Hii @sduenas ， we just had a holiday in China(Oct 1 - Oct 7), I will take care of it recently and close this pr for now.

**Pull request closed without merging**
