### PR TITLE
[pagure] Fix failing tests

### PR DESCRIPTION
**Pull request by animeshk08**
This commit fixes failing tests
for Pagure backend.

Signed-off-by: Animesh Kumar <animuz111@gmail.com>

### CODE REVIEW

**Comment by animeshk08** [comment]
Hi @valeriocos. There were some issues with the tests in Pagure backend. Hence the recent pull had failing tests. I am terribly sorry to let it come into production I will be more careful in the future.

**Comment by valeriocos** [comment]
No worries @animeshk08 , can you update the backend version?

Recently we have developed a tool to ease some tasks of the release procedure. One of the script allows to create notes about the changes in the code (details can be found at https://github.com/Bitergia/release-tools#changelog). Would you like to test it for this PR and provide feedback (e.g., usability, usefulness)? Thanks

**Comment by animeshk08** [comment]
Thanks, @valeriocos. Should I update the version to 0.1.1 or 0.2.0?

**Comment by valeriocos** [comment]
0.1.1, thanks!

**Comment by animeshk08** [comment]
Done!

**Pull request merged**
