### PR TITLE
[DOCS] Fixes typographical errors in `docs/contributing.rst`

### PR DESCRIPTION
**Pull request by SteveKola**
cc: @vchrombie

### CODE REVIEW

**Comment by vchrombie** [comment]
Hi @SteveKola, thanks for the PR.
Would you mind fixing the commit message? It looks incomplete.
Also, it would be great if you can add a small commit description too.

**Comment by SteveKola** [comment]
> Hi @SteveKola, thanks for the PR.
> Would you mind fixing the commit message? It looks incomplete.
> Also, it would be great if you can add a small commit description too.

Fixed.

**Review by vchrombie — APPROVED** [review]
LGTM, thanks for the PR.

**Review by sduenas — APPROVED** [review]
LGTM

**Comment by sduenas** [comment]
Merged.

**Pull request closed without merging**
