### PR TITLE
Update pyproject.toml

### PR DESCRIPTION
**Pull request by suhascv**
updating pyproject.toml with 'setuptools' version to solve this [issue](https://github.com/chaoss/grimoirelab-perceval/issues/720)

### CODE REVIEW

**Comment by vchrombie** [comment]
Hi @suhascv, thanks for your PR but we need some more changes here to make this perfect. I think I can help to make this perfect meanwhile we decide on [this comment](https://github.com/chaoss/grimoirelab-perceval/issues/720#issuecomment-785699601).

There are some extra commits in your branch which are not necessary for the PR. Kindly rebase with the upstream and force pus the branch.

```
git fetch upstream
git rebase upstream/master
git push -f origin master
```

If you didn't set the upstream, you can add it now.
```
git remote -v
git remote add upstream https://github.com/chaoss/grimoirelab-perceval
```

Please let me know if you need any more help. :)

**Comment by vchrombie** [comment]
Please let us know once you add the changes too so that we can have a review.
Thanks.

**Comment by suhascv** [comment]
@vchrombie  I tried to make the above changes, I get the following error for ```git push -f origin master ```
## error
```
remote: Permission to chaoss/grimoirelab-perceval-weblate.git denied to suhascv.
fatal: unable to access 'https://github.com/chaoss/grimoirelab-perceval-weblate.git/':
The requested URL returned error: 403 ```

**Comment by vchrombie** [comment]
> ```
> remote: Permission to chaoss/grimoirelab-perceval-weblate.git denied to suhascv.
> fatal: unable to access 'https://github.com/chaoss/grimoirelab-perceval-weblate.git/':
> The requested URL returned error: 403 ```
> ```

Hi @suhascv, looks like you are not in the right repository. You should be cloning your fork and making changes to the branch in your fork.
```
git clone https://github.com/suhascv/grimoirelab-perceval/
cd grimoirelab-perceval
```

I see you closed the PR, that's not a big problem. Please let us know if you need any help.

**Comment by vchrombie** [comment]
@suhascv are you interested to re-open this PR and work on the issue?

Let me know if you need any help.

**Comment by vchrombie** [comment]
Hi @suhascv, do you have the time to re-open and work on these PRs?
Let me know if it is not possible, I'm ready to take over it.

**Comment by vchrombie** [comment]
I'm taking up this PR.

**Pull request closed without merging**
