### PR TITLE
[githubql] Add PullRequestReview event

### PR DESCRIPTION
**Pull request by zhquan**
This code fetches PullRequestReview events to know the review
state:
- APPROVED
- CHANGES_REQUESTED
- COMMENTED
- DISMISSED
- PENDING

Test added accordingly.

Signed-off-by: Quan Zhou <quan@bitergia.com>

### CODE REVIEW

**Review by sduenas — CHANGES_REQUESTED** [review]
Can you update the version of the backend to `0.4.0`?

**Comment by vchrombie** [comment]
Also, do you think we can start adding release notes from now? We can start using release tools for the upcoming release.
Please let me know your thoughts on it.

@sduenas @zhquan

**Comment by sduenas** [comment]
> Also, do you think we can start adding release notes from now? We can start using release tools for the upcoming release.
> Please let me know your thoughts on it.
> 
> @sduenas @zhquan

I want to start doing that soon. Let's wait until we release `0.18.0` to start doing that.

**Review by sduenas — APPROVED** [review]
LGTM

**Pull request closed without merging**
