### PR TITLE
URL changed to hostname

### LINKED ISSUE #368: [gerrit] url should be hostname
Currently, the help for `perceval gerrit` reads:

```
usage: perceval [-h] [--category CATEGORY] [--tag TAG] [--from-date FROM_DATE]
                ...
                url
```

However, the "url" is not really an url, but the host name where ssh access to the Gerrit instance is granted. I would change this to "hostname".

If this change is done, very likely variable names and paramerters in the Python interface should also be changed from "url" to "hostname".

Do others agree with this change?

### PR DESCRIPTION
**Pull request by Prabhat-IIT**
Fixed #368

### CODE REVIEW

**Comment by Prabhat-IIT** [comment]
@jgbarah  please review it.

**Comment by Prabhat-IIT** [comment]
@jgbarah

**Comment by sduenas** [comment]
Thanks for your PR @Prabhat-IIT . I merged it in a different commit because I had to change your comment message and increase the version of the backend.

**Comment by jgbarah** [comment]
Great! Thanks to all of you!

**Comment by Prabhat-IIT** [comment]
Thanks for merging the PR :smiley:

**Pull request closed without merging**
