### PR TITLE
[confluence] Skip contents if 'when' attribute is missing

### PR DESCRIPTION
**Pull request by valeriocos**
This PR allows to skip the historical contents not having the 'when' attribute, which is used to calculated the `updated_on` value of the JSON output produced by Perceval.

### CODE REVIEW

**Comment by valeriocos** [comment]
> You also have to add the commit with the tests to the same commit where you are adding this check. Remember that commits should work by their own most of the times and tests should be part of the same unit.

Can you provide a reference for your statement?

**Comment by valeriocos** [comment]
> I need more info about why a concurse entry doesn't have when attribute. Can you give me an example?

I'll post here the failing document

**Comment by valeriocos** [comment]
```
{
  'id': '10782066', 
  'type': 'attachment', 
  'status': 'historical', 
  'title': 'Security@onap develepors event.pdf', 
  'history': {
      'latest': False, 
      'createdBy': {
          'type': 'known', 
          'username': 'KennyPaul', 
          'userKey': '2c9e48aa5b161cdb015b452be9430039', 
          'profilePicture': {
              'path': '/download/attachments/3245160/user-avatar', 
              'width': 48, 
              'height': 48, 
              'isDefault': False
          }, 
          'displayName': 'Kenny Paul', 
          '_links': {
              'self': 'https://wiki.onap.org/rest/api/user?key=2c9e48aa5b161cdb015b452be9430039'}, 
              '_expandable': {'status': ''}
          }, 
          'createdDate': '2017-07-24T17:26:49.000Z', 
          '_links': {
              'self': 'https://wiki.onap.org/rest/api/content/10782066/history'
          }, 
          '_expandable': {
              'lastUpdated': '', 
              'previousVersion': '', 
              'contributors': '', 'nextVersion': ''
          }
  }, 
  'version': {
       'by': {
            'type': 'anonymous', 
             'profilePicture': {
                  'path': '/s/en_GB/7901/58be3fa11e9ad58113c0ea45e7063389a7c7d344/_/images/icons/profilepics/anonymous.svg', 
                  'width': 48, 
                  'height': 48, 
                  'isDefault': True
              }, 
              'displayName': 'Anonymous'
        }, 
        'message': 'Presenter: Steve Terrill', 
        'number': 1, 
        'minorEdit': False, 
        'hidden': False, 
        '_links': {
            'self': 'https://wiki.onap.org/rest/experimental/content/10782066/version/1'
        }, 
        '_expandable': {
           'content': '/rest/api/content/10782066?status=historical&version=1'
        }
  },
  'body': {
      'storage': {
         'value': '', 
         'representation': 'storage', 
         '_expandable': {
              'content': '/rest/api/content/10782066?status=historical&version=1'
          }
      }, 
      '_expandable': {
          'editor': '', 
          'view': '', 
           'export_view': '', 
           'styled_view': '', 
          'anonymous_export_view': ''
      }
  }, 
  'metadata': {
      'comment': 'Presenter: Steve Terrill', 
      'mediaType': 'application/pdf'
  }, 
  'extensions': {
      'mediaType': 'application/pdf', 
      'fileSize': 419987, 
      'comment': 'Presenter: Steve Terrill'
  }, 
  '_links': {
      'webui': '/pages/viewpage.action?pageId=8231717&preview=%2F8231717%2F10782066%2FSecurity@onap+develepors+event.pdf', 
      'download': '/download/attachments/8231717/Security@onap%20develepors%20event.pdf?version=1&api=v2', 
      'collection': '/rest/api/content', 
      'base': 'https://wiki.onap.org', 
      'context': '', 
      'self': 'https://wiki.onap.org/rest/api/content/10782066?status=historical&version=1'
  }, 
  '_expandable': {
      'container': '/rest/api/content/8231717', 
      'operations': '', 
      'children': '/rest/api/content/10782066/child?parentVersion=1', 'restrictions': '/rest/api/content/10782066/restriction/byOperation',
      'ancestors': '', 
      'descendants': '/rest/api/content/10782066/descendant', 'space': '/rest/api/space/DW'
  }
}
```

**Comment by valeriocos** [comment]
I have updated the PR, and added two more commits (which could go to other to PRs). The former commit fixes a typo, while the latter increases the test coverage.

**Comment by sduenas** [comment]
The sample where Perceval is failing is an `attachment`. Would it be possible that's the cause? Maybe the first time an attachment is created it doesn't have that value, and the value can be obtained from other field like `createDate`. It will be great to have more of the these documents where this is failing to try to find a trend. 

I wouldn't like to add this check without knowing for sure what's going.

**Comment by sduenas** [comment]
> > You also have to add the commit with the tests to the same commit where you are adding this check. Remember that commits should work by their own most of the times and tests should be part of the same unit.
> 
> I have no problem in squashing the commits, however do you have a reference about the statement above?

Of course. Commits should be kept small adding little changes once at a time, that work as a whole without introducing new errors. These offer several benefits:

- it's easier to review
- it's easier to spot possible errors in the code
- it's easier to test
- it's easier to roll back to a point in the code with the software was working, in case this commit introduces an error,
- it's easier to add hot fixes to stable branches via cherrypicking or merging feature branches

As good commits should keep those properties it's a good practice to add unit tests in the same commit. Specially in continuous integration, where releases are generated and tested which each 
commit.

How will you roll back your code if one of the changes you introduced recently fails and your tests were added after this feature? How you would be sure those other changes work?

https://www.freshconsulting.com/atomic-commits/

**Comment by valeriocos** [comment]
Find below a couple of attachments with `when` attribute
```
{
    "_expandable": {
        "ancestors": "",
        "children": "/rest/api/content/1015971/child",
        "container": "/rest/api/content/1015829",
        "descendants": "/rest/api/content/1015971/descendant",
        "operations": "",
        "restrictions": "/rest/api/content/1015971/restriction/byOperation",
        "space": "/rest/api/space/DW"
    },
    "_links": {
        "base": "https://wiki.onap.org",
        "collection": "/rest/api/content",
        "context": "",
        "download": "/download/attachments/1015829/lock-icon.png?version=1&modificationDate=1481820134000&api=v2",
        "self": "https://wiki.onap.org/rest/api/content/1015971",
        "thumbnail": "/download/thumbnails/1015829/lock-icon.png?api=v2",
        "webui": "/display/DW/Developer+Wiki?preview=%2F1015829%2F1015971%2Flock-icon.png"
    },
    "ancestors": [],
    "body": {
        "_expandable": {
            "anonymous_export_view": "",
            "editor": "",
            "export_view": "",
            "styled_view": "",
            "view": ""
        },
        "storage": {
            "_expandable": {
                "content": "/rest/api/content/1015971"
            },
            "representation": "storage",
            "value": ""
        }
    },
    "content_url": "https://wiki.onap.org/display/DW/Developer+Wiki?preview=%2F1015829%2F1015971%2Flock-icon.png",
    "extensions": {
        "comment": "",
        "fileSize": 3448,
        "mediaType": "image/png"
    },
    "history": {
        "_expandable": {
            "contributors": "",
            "lastUpdated": "",
            "nextVersion": "",
            "previousVersion": ""
        },
        "_links": {
            "self": "https://wiki.onap.org/rest/api/content/1015971/history"
        },
        "createdBy": {
            "displayName": "Anonymous",
            "profilePicture": {
                "height": 48,
                "isDefault": true,
                "path": "/s/en_GB/7901/58be3fa11e9ad58113c0ea45e7063389a7c7d344/_/images/icons/profilepics/anonymous.svg",
                "width": 48
            },
            "type": "anonymous"
        },
        "createdDate": "2016-12-15T16:42:14.000Z",
        "latest": true
    },
    "id": "1015971",
    "metadata": {
        "mediaType": "image/png"
    },
    "status": "current",
    "title": "lock-icon.png",
    "type": "attachment",
    "version": {
        "_expandable": {
            "content": "/rest/api/content/1015971"
        },
        "_links": {
            "self": "https://wiki.onap.org/rest/experimental/content/1015971/version/1"
        },
        "by": {
            "displayName": "Anonymous",
            "profilePicture": {
                "height": 48,
                "isDefault": true,
                "path": "/s/en_GB/7901/58be3fa11e9ad58113c0ea45e7063389a7c7d344/_/images/icons/profilepics/anonymous.svg",
                "width": 48
            },
            "type": "anonymous"
        },
        "hidden": false,
        "message": "",
        "minorEdit": true,
        "number": 1,
        "when": "2016-12-15T16:42:14.000Z"
    }
}
```

**Comment by valeriocos** [comment]
The second attachment
```
{
    "_expandable": {
        "ancestors": "",
        "children": "/rest/api/content/1016737/child",
        "container": "/rest/api/content/1015831",
        "descendants": "/rest/api/content/1016737/descendant",
        "operations": "",
        "restrictions": "/rest/api/content/1016737/restriction/byOperation",
        "space": "/rest/api/space/DW"
    },
    "_links": {
        "base": "https://wiki.onap.org",
        "collection": "/rest/api/content",
        "context": "",
        "download": "/download/attachments/1015831/image2016-12-20_14-31-28.png?version=1&modificationDate=1482244290000&api=v2",
        "self": "https://wiki.onap.org/rest/api/content/1016737",
        "thumbnail": "/download/thumbnails/1015831/image2016-12-20_14-31-28.png?api=v2",
        "webui": "/pages/viewpage.action?pageId=1015831&preview=%2F1015831%2F1016737%2Fimage2016-12-20_14-31-28.png"
    },
    "ancestors": [],
    "body": {
        "_expandable": {
            "anonymous_export_view": "",
            "editor": "",
            "export_view": "",
            "styled_view": "",
            "view": ""
        },
        "storage": {
            "_expandable": {
                "content": "/rest/api/content/1016737"
            },
            "representation": "storage",
            "value": ""
        }
    },
    "content_url": "https://wiki.onap.org/pages/viewpage.action?pageId=1015831&preview=%2F1015831%2F1016737%2Fimage2016-12-20_14-31-28.png",
    "extensions": {
        "comment": "",
        "fileSize": 120162,
        "mediaType": "image/png"
    },
    "history": {
        "_expandable": {
            "contributors": "",
            "lastUpdated": "",
            "nextVersion": "",
            "previousVersion": ""
        },
        "_links": {
            "self": "https://wiki.onap.org/rest/api/content/1016737/history"
        },
        "createdBy": {
            "_expandable": {
                "status": ""
            },
            "_links": {
                "self": "https://wiki.onap.org/rest/api/user?key=2c9e48aa59d2de1c015a3e6d3aeb0016"
            },
            "displayName": "Unknown User (rnnavarro)",
            "profilePicture": {
                "height": 48,
                "isDefault": true,
                "path": "/images/icons/profilepics/default.svg",
                "width": 48
            },
            "type": "known",
            "userKey": "2c9e48aa59d2de1c015a3e6d3aeb0016",
            "username": "rnnavarro"
        },
        "createdDate": "2016-12-20T14:31:30.000Z",
        "latest": true
    },
    "id": "1016737",
    "metadata": {
        "mediaType": "image/png"
    },
    "status": "current",
    "title": "image2016-12-20_14-31-28.png",
    "type": "attachment",
    "version": {
        "_expandable": {
            "content": "/rest/api/content/1016737"
        },
        "_links": {
            "self": "https://wiki.onap.org/rest/experimental/content/1016737/version/1"
        },
        "by": {
            "_expandable": {
                "status": ""
            },
            "_links": {
                "self": "https://wiki.onap.org/rest/api/user?key=2c9e48aa59d2de1c015a3e6d3aeb0016"
            },
            "displayName": "Unknown User (rnnavarro)",
            "profilePicture": {
                "height": 48,
                "isDefault": true,
                "path": "/images/icons/profilepics/default.svg",
                "width": 48
            },
            "type": "known",
            "userKey": "2c9e48aa59d2de1c015a3e6d3aeb0016",
            "username": "rnnavarro"
        },
        "hidden": false,
        "message": "",
        "minorEdit": true,
        "number": 1,
        "when": "2016-12-20T14:31:30.000Z"
    }
}
```

**Comment by valeriocos** [comment]
> Of course. Commits should be kept small adding little changes once at a time, that work as a whole without introducing new errors. These offer several benefits: .....
> 
> https://www.freshconsulting.com/atomic-commits/

It seems that there is no common agreement of what to put inside `atomic commits` and I didn't find any "official" documentation beyond blogs and posts (see list below), thus it seems that the way of committing changes aligns more to a project convention, than a general rule. Anyway, I'm totally fine with the way you think is best, and I'm wondering if this should be written somewhere to define some contribution guidelines (which could be apply to all repos under the GrimoireLab umbrella).
If you agree, we can keep talking off-line about this (just to keep this issue focused on the confluence issue) :)

- https://www.codewithjason.com/atomic-commits-testing/
- https://stackoverflow.com/questions/38155592/atomic-commits-best-practice
- https://stackoverflow.com/questions/6228550/should-change-to-code-be-committed-separately-from-corresonding-change-to-test-s

**Comment by valeriocos** [comment]
Here another attachment including a pdf
```
{
    "_expandable": {
        "ancestors": "",
        "children": "/rest/api/content/45291913/child",
        "container": "/rest/api/content/45291881",
        "descendants": "/rest/api/content/45291913/descendant",
        "operations": "",
        "restrictions": "/rest/api/content/45291913/restriction/byOperation",
        "space": "/rest/api/space/GVNFM"
    },
    "_links": {
        "base": "https://wiki.onap.org",
        "collection": "/rest/api/content",
        "context": "",
        "download": "/download/attachments/45291881/NAT%20Usecase%26Requirement.pdf?version=1&modificationDate=1485177604000&api=v2",
        "self": "https://wiki.onap.org/rest/api/content/45291913",
        "webui": "/display/GVNFM/M0-Project+Plan?preview=%2F45291881%2F45291913%2FNAT+Usecase%26Requirement.pdf"
    },
    "ancestors": [],
    "body": {
        "_expandable": {
            "anonymous_export_view": "",
            "editor": "",
            "export_view": "",
            "styled_view": "",
            "view": ""
        },
        "storage": {
            "_expandable": {
                "content": "/rest/api/content/45291913"
            },
            "representation": "storage",
            "value": ""
        }
    },
    "content_url": "https://wiki.onap.org/display/GVNFM/M0-Project+Plan?preview=%2F45291881%2F45291913%2FNAT+Usecase%26Requirement.pdf",
    "extensions": {
        "comment": "",
        "fileSize": 250176,
        "mediaType": "application/pdf"
    },
    "history": {
        "_expandable": {
            "contributors": "",
            "lastUpdated": "",
            "nextVersion": "",
            "previousVersion": ""
        },
        "_links": {
            "self": "https://wiki.onap.org/rest/api/content/45291913/history"
        },
        "createdBy": {
            "_expandable": {
                "status": ""
            },
            "_links": {
                "self": "https://wiki.onap.org/rest/api/user?key=2c9e48aa59d2de1c015a8ca29e150083"
            },
            "displayName": "Maopeng Zhang",
            "profilePicture": {
                "height": 48,
                "isDefault": true,
                "path": "/images/icons/profilepics/default.svg",
                "width": 48
            },
            "type": "known",
            "userKey": "2c9e48aa59d2de1c015a8ca29e150083",
            "username": "maopengzhang"
        },
        "createdDate": "2017-01-23T13:20:04.000Z",
        "latest": true
    },
    "id": "45291913",
    "metadata": {
        "mediaType": "application/pdf"
    },
    "status": "current",
    "title": "NAT Usecase&Requirement.pdf",
    "type": "attachment",
    "version": {
        "_expandable": {
            "content": "/rest/api/content/45291913"
        },
        "_links": {
            "self": "https://wiki.onap.org/rest/experimental/content/45291913/version/1"
        },
        "by": {
            "_expandable": {
                "status": ""
            },
            "_links": {
                "self": "https://wiki.onap.org/rest/api/user?key=2c9e48aa59d2de1c015a8ca29e150083"
            },
            "displayName": "Maopeng Zhang",
            "profilePicture": {
                "height": 48,
                "isDefault": true,
                "path": "/images/icons/profilepics/default.svg",
                "width": 48
            },
            "type": "known",
            "userKey": "2c9e48aa59d2de1c015a8ca29e150083",
            "username": "maopengzhang"
        },
        "hidden": false,
        "message": "",
        "minorEdit": true,
        "number": 1,
        "when": "2017-01-23T13:20:04.000Z"
    }
}
```

**Comment by valeriocos** [comment]
The failing document has more versions, which correctly have the `when` attribute. Given the version below and the examples of other attachments (above), it seems that the problem is in the upstream API, and I'm not sure it should be handled in Perceval.
```
{
  'id': '10782066', 
  'type': 'attachment', 
  'status': 'current', 
  'title': 'Security@onap develepors event.pdf', 
  'history': {
    'latest': True, 
    'createdBy': {
      'type': 'known', 
      'username': 'KennyPaul', 
      'userKey': '2c9e48aa5b161cdb015b452be9430039', 
      'profilePicture': {
        'path': '/download/attachments/3245160/user-avatar', 
        'width': 48, 
        'height': 48, 
        'isDefault': False
      }, 
      'displayName': 'Kenny Paul', 
      '_links': {
        'self': 'https://wiki.onap.org/rest/api/user?key=2c9e48aa5b161cdb015b452be9430039'
      }, 
      '_expandable': {
        'status': ''
      }
    }, 
    'createdDate': '2017-07-24T17:26:49.000Z', 
    '_links': {
      'self': 'https://wiki.onap.org/rest/api/content/10782066/history'
    }, 
    '_expandable': {
      'lastUpdated': '', 
      'previousVersion': '', 
      'contributors': '', 
      'nextVersion': ''
    }
  }, 
  'version': {
    'by': {
      'type': 'known', 
      'username': 'KennyPaul', 
      'userKey': '2c9e48aa5b161cdb015b452be9430039', 
      'profilePicture': {
        'path': '/download/attachments/3245160/user-avatar', 
        'width': 48, 
        'height': 48, 
        'isDefault': False
      }, 
      'displayName': 'Kenny Paul', 
      '_links': {
        'self': 'https://wiki.onap.org/rest/api/user?key=2c9e48aa5b161cdb015b452be9430039'
      }, 
      '_expandable': {
        'status': ''
      }
    }, 
    'when': '2017-07-24T17:26:49.000Z', 
    'message': 'Presenter: Steve Terrill', 
    'number': 2, 
    'minorEdit': False, 
    'hidden': False, 
    '_links': {
      'self': 'https://wiki.onap.org/rest/experimental/content/10782066/version/2'
    }, 
    '_expandable': {
      'content': '/rest/api/content/10782066'
    }
  }, 
  'body': {
    'storage': {
      'value': '', 
      'representation': 'storage', 
      '_expandable': {
        'content': '/rest/api/content/10782066'
      }
    }, 
    '_expandable': {
      'editor': '', 
      'view': '', 
      'export_view': '', 
      'styled_view': '', 
      'anonymous_export_view': ''
    }
  }, 
  'metadata': {
    'comment': 'Presenter: Steve Terrill', 
    'mediaType': 'application/pdf'
  }, 
  'extensions': {
    'mediaType': 'application/pdf', 
    'fileSize': 419987, 
    'comment': 'Presenter: Steve Terrill'
  }, 
  '_links': {
    'webui': '/pages/viewpage.action?pageId=8231717&preview=%2F8231717%2F10782066%2FSecurity@onap+develepors+event.pdf', 
    'download': '/download/attachments/8231717/Security@onap%20develepors%20event.pdf?version=2&modificationDate=1500917209000&api=v2', 
    'collection': '/rest/api/content', 
    'base': 'https://wiki.onap.org', 
    'context': '', 
    'self': 'https://wiki.onap.org/rest/api/content/10782066'
  },
  '_expandable': {
    'container': '/rest/api/content/8231717', 
    'operations': '', 
    'children': '/rest/api/content/10782066/child', 
    'restrictions': '/rest/api/content/10782066/restriction/byOperation', 
    'ancestors': '', 
    'descendants': '/rest/api/content/10782066/descendant', 
    'space': '/rest/api/space/DW'
  }
}
```

**Pull request merged**
