### PR TITLE
[backend] Add missing sanitize for archive

### PR DESCRIPTION
**Pull request by animeshk08**
Fixes: #638 
This commit adds missing method to sanitize the payload
of a HTTP request before storing/retrieving archived items
to some of the backends that required it.

Signed-off-by: Animesh Kumar <animuz111@gmail.com>

### CODE REVIEW

**Comment by animeshk08** [comment]
Hi, @valeriocos I have opened a PR based on the discussions here: https://github.com/chaoss/grimoirelab-perceval/pull/632#discussion_r396077599

Please have a look let me know if any changes are required :)

**Comment by animeshk08** [comment]
Sorry about the long docstrings/statements. I have update the methods. Please have a look now :)

**Comment by valeriocos** [comment]
No worries, thank you for the quick reaction @animeshk08 !

Can you do the following?
- split the changes in different commits (a commit per backend and corresponding test)
- upgrade the minor number of the backends

In the commit message please mention that tests have been added and the new version of the backend. As a reference, you can follow this commit https://github.com/chaoss/grimoirelab-perceval/commit/08006aec1e63a6d1b862eb4199651e2a3bdfc91f 

Sorry for not mentioning this before.

**Comment by animeshk08** [comment]
Hi @valeriocos. I have updated the commits :)

**Comment by valeriocos** [comment]
@animeshk08 thank you for your contribution! I have rebased your branch since not in sync with `master`

**Comment by animeshk08** [comment]
Thanks @valeriocos.  

> I have rebased your branch since not in sync with master
Sorry about this I will try to avoid this in future.

**Comment by valeriocos** [comment]
No worries :)

**Pull request closed without merging**
