### PR TITLE
[docs]  Add OSF community backend

### PR DESCRIPTION
**Pull request by Alch-Emi**
The OSF perceval backend was forked from the weblate backend, and developed primarily by Open@RIT member @suhascv, with some contributions from me.  It currently supports collecting a number of global statistics about OSF, as well as activity logs and forks for specific projects.

This commit adds a link to the perceval-osf backend to the list of community-maintained backends in the README.  We at open@rit would greatly appreciate the inclusion!

—Emi

### CODE REVIEW

**Review by vchrombie — APPROVED** [review]
LGTM! Thanks for your contribution @Alch-Emi and for working on the backend.

cc @suhascv @Nolski

**Comment by sduenas** [comment]
I'm curious about the differences between this backend and weblate one? @Alch-Emi do you know anything about that?

**Comment by Alch-Emi** [comment]
Yeah, I can definitely try to fill in any questions you have!  Suhas is the lead dev, but I've worked with the codebase a little.  The main differences stem from the fact that perceval-osf works with osf.io and so the metrics it retrieves are tailored to what is available on OSF.  You can see [the supported categories][1] on the README if you're curious.  Are there any specific differences you would want to know more about?

[1]: https://gitlab.com/open-rit/perceval-osf#valid-osf-categories

**Comment by sduenas** [comment]
Thanks for the info. I don't know why I thought osf.io was a weblate instance, so I thought it would be nice to have any change integrated upstream.

**Pull request merged**
