### PR TITLE
[doc] Update help messages for "from-date" and "to-date" params

### PR DESCRIPTION
**Pull request by harshalmittal4**
This PR updates the help messages for "from-date" and "to-date" params to include some possible date formats.
Addresses #503.

### CODE REVIEW

**Comment by harshalmittal4** [comment]
```
[docs] Update help messages for "from-date" and "to-date" fields
    
This updates help messages for "from-date" and "to-date" fields to show some date formats
```
Hey @valeriocos, does this seem reasonable ^
(sorry bothering you for minor details :sweat_smile: )

**Comment by valeriocos** [comment]
no worries @harshalmittal4 :) yes, probably using `params` is better `fields`, and the commit description should end with a full stop. Once this is done, I guess the PR could be merged @sduenas

**Comment by harshalmittal4** [comment]
@valeriocos @sduenas done.

**Comment by valeriocos** [comment]
> - the commit message is too long (KO)
> - a space is needed between the tag and commit title (OK)
> - "the" seems not needed at the end of the commit message (OK)

Please @harshalmittal4 modify the commit message as follow, thank you!
```
[docs] Update help messages for "from-date" and "to-date" params

This code updates the help messages for "from-date" and "to-date" 
params to include some possible date formats.

Signed-off-by: Harshal Mittal <harshalmittal4@gmail.com>
```

**Comment by harshalmittal4** [comment]
Done @valeriocos, I need to work on my commit messages, would try to be more detailed and to the point from next onwards. Thanks.

**Comment by valeriocos** [comment]
Thanks @harshalmittal4 
@sduenas if you agree, this PR could be merged

**Comment by valeriocos** [comment]
@harshalmittal4 ping! :)

**Comment by harshalmittal4** [comment]
```
help="fetch items updated since this date (e.g., YYYY-MM-DD, MM-DD-YYYY, "YYYY-MM-DD HH:mm:SS", "YYYY-MM-DD HH:mm:SS +HH:MM", etc.)"
help="fetch items updated before this date (e.g., YYYY-MM-DD, MM-DD-YYYY, "YYYY-MM-DD HH:mm:SS", "YYYY-MM-DD HH:mm:SS +HH:MM", etc.)"
```
Thanks @valeriocos. was about to address this :)
I think these show the possible formats, although they are a bit long. @valeriocos, @sduenas, please share your thoughts on this.

**Comment by valeriocos** [comment]
Thanks @harshalmittal4, some thoughts :) 
- the `etc.` at the end doesn't seem to be needed
- maybe 4 examples are too much
- the examples are not consistent, some of them have double quotes others don't.

maybe we could try something like this:
`help="fetch items updated since this date (e.g., (YYYY-MM-DD|..|MM-DD-YYYY)(HH:mm:SS)?(+HH:MM)?)"` 

what do you think @sduenas , @harshalmittal4 ?

**Comment by harshalmittal4** [comment]
>the examples are not consistent, some of them have double quotes others don't.

Yes, I know. Actually the examples having double quotes can't work without them due to having spaces in between :sweat_smile: 

>help="fetch items updated since this date (e.g., (YYYY-MM-DD|..|MM-DD-YYYY)(HH:mm:SS)?(+HH:MM)?)"
```
help="fetch items updated since this date (e.g, "YYYY-MM-DD|..|MM-DD-YYYY [HH:mm:SS] [+HH:MM]" )"
```
Does this seem more understadable ^ @valeriocos ?

**Comment by valeriocos** [comment]
thank you @harshalmittal4 , It's ok for me. Any thoughts/suggestion @sduenas ?

**Comment by sduenas** [comment]
> thank you @harshalmittal4 , It's ok for me. Any thoughts/suggestion @sduenas ?

Why don't say it supports [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) with a small example and that's all?

**Comment by harshalmittal4** [comment]
```
help="fetch items updated since this date (ISO 8601 format, e.g., "YYYY-MM-DD HH:mm:SS +|- HH:MM")"
```
Hey @sduenas, @valeriocos , I am a little unsure about the example to use :wink:, please see, if this would look good..

**Comment by valeriocos** [comment]
It looks ok for me @harshalmittal4

**Comment by harshalmittal4** [comment]
@sduenas please review :slightly_smiling_face:

**Comment by sduenas** [comment]
@harshalmittal4 looks good to me too, please update the PR with that message.

**Comment by harshalmittal4** [comment]
thanks @sduenas, have made the update ;)

**Comment by valeriocos** [comment]
please @harshalmittal4 coud you rebase* your PR to have it aligned with the master branch, thanks :)

*if needed
```
git fetch upstream
git rebase upstream/master
```
where upstream is `https://github.com/chaoss/grimoirelab-perceval`

**Comment by valeriocos** [comment]
ping @harshalmittal4

**Comment by harshalmittal4** [comment]
Sorry @valeriocos, missed that rebasing is needed while pushing earlier (since both the HEADs were at `Update version number to ...`  commit, although just now saw that the 2 commits were different :stuck_out_tongue:),
I have updated the PR now, and it is ready to be merged :)

**Comment by valeriocos** [comment]
great @harshalmittal4 , thank you!

**Pull request merged**
