### PR TITLE
Add readthedocs badge

### PR DESCRIPTION
**Pull request by jgbarah**

### CODE REVIEW

**Comment by sduenas** [comment]
@jgbarah please fix the conflics before merging it.

**Comment by jgbarah** [comment]
> @jgbarah please fix the conflics before merging it.

Done

**Comment by jgbarah** [comment]
Anything about this, @sduenas ?

**Comment by jgbarah** [comment]
Sorry for asking again... ;-)

**Comment by jgbarah** [comment]
???

**Comment by jgbarah** [comment]
???

**Pull request closed without merging**
