### PR TITLE
[slack] Update resource endpoints

### PR DESCRIPTION
**Pull request by animeshk08**
Fixes: #655 
This commit updates the resource endpoints
to fetch the messages and information of a
channel.
The tests have been updated accordingly.
The backend version is now 0.9.1

Signed-off-by: Animesh Kumar <animuz111@gmail.com>

### CODE REVIEW

**Comment by animeshk08** [comment]
The following are the changes due to the new of endpoints:
* Additions to `channel_info`:
```
"is_ext_shared": false,
"is_group": false,
"is_im": false,
"is_pending_ext_shared": false,
"parent_conversation": null,
"pending_connected_team_ids": [],
"pending_shared": [],
"shared_team_ids": [
                "T01281XCKTR"
            ],
```
* Deletions from `channel_info`:
```
"latest": {
                "blocks": [
                    {
                        "block_id": "WoeZ4",
                        "elements": [
                            {
                                "elements": [
                                    {
                                        "text": "hello",
                                        "type": "text"
                                    }
                                ],
                                "type": "rich_text_section"
                            }
                        ],
                        "type": "rich_text"
                    }
                ],
                "client_msg_id": "0c9d5905-c9fc-4f71-a067-b48fe248ebee",
                "parent_user_id": "U01289NA1HV",
                "team": "T01281XCKTR",
                "text": "hello",
                "thread_ts": "1588129375.001100",
                "ts": "1588132356.001800",
                "type": "message",
                "user": "U01289NA1HV"
            },
            "members": [
                "U012UUR4V6Y",
                "U01289NA1HV",
                "U012MC9PEER"
            ]
``` 

*  I have manually tried the slack implementation on various kinds of messages and did not find any change in the history API response.

Based on the current implementation of the enricher for slack I don't think any extra fields are to be enriched(**please let me know if any of the above addition is to be enriched**) only the `latest` may be removed from the raw index mapping of slack.

**Comment by animeshk08** [comment]
Hi @valeriocos, please verify this comment also https://github.com/chaoss/grimoirelab-perceval/issues/655#issuecomment-620636362. I will update the documentation accordingly :)
Thanks

**Comment by sduenas** [comment]
@animeshk08 would you mind to add in your commit message more information about the change? Information like you wrote in the original message would be very useful. What fields changed and the link to the post in slack blog.

**Comment by animeshk08** [comment]
Thank you for the suggestion @sduenas :)

**Pull request closed without merging**
